const SHOP_DATA = [
    {
        id: 1,
        title: 'Vitamins',
        routeName: 'Vitamins',
        items: [
    {"id":"440",
    "name":"Multi-Vitamin (90 capsules)",
    "description":"A daily dose of our Multi-Vitamins fulfills a day's nutritional needs for over 12 vitamins and minerals.",
    "image_title":"multi-vitamin_600px",
    "image":"https://hplussport.com/wp-content/uploads/2016/12/multi-vitamin_600px.png",
    "size": "large",
    "price": "200" },
    {"id":"471",
    "name":"Flaxseed Oil 1000 mg (90 capsules)",
    "description":"Our Flaxseed Oil contains Omegas 3, 6, and 9 for a heart-healthy option without the use of fish oil.",
    "image_title":"flaxseed-oil_600px",
    "image":"https://hplussport.com/wp-content/uploads/2016/12/flaxseed-oil_600px.png",
    "size": "large",
    "price": "250"},
    {"id":"472",
    "name":"Magnesium 250 mg (100 tablets)",
    "description":"Magnesium is critical to many bodily processes, and supports nerve, muscle, and heart function.",
    "image_title":"magnesium_600px",
    "image":"https://hplussport.com/wp-content/uploads/2016/12/magnesium_600px.png",
    "size": "large",
    "price": "98"},
    {"id":"473",
    "name":"Iron 65 mg (150 caplets)",
    "description":"Iron is essential for transporting oxygen in the body and for the formation of red blood cells.",
    "image_title":"iron_600px",
    "image":"https://hplussport.com/wp-content/uploads/2016/12/iron_600px.png",
    "size": "large",
    "price": "300"},
    {"id":"474",
    "name":"Calcium 400 IU (150 tablets)",
    "description":"Our Calcium supports strong bones and teeth and may help prevent osteoporosis.<strong>\u00c2\u00a0</strong>",
    "image_title":"calcium_600px",
    "image":"https://hplussport.com/wp-content/uploads/2016/12/calcium_600px.png",
    "size": "large",
    "price": "400"},
    {"id":"475",
    "name":"Vitamin D3 1000 IU (100 tablets)",
    "description":"Vitamin D<sub>3</sub> is the body's preferred form of Vitamin D, and helps support bone, teeth, and immune health.",
    "image_title":"vitamin-d_600px",
    "image":"https://hplussport.com/wp-content/uploads/2016/12/vitamin-D_600px.png",
    "size": "large",
    "price": "500"},
    {"id":"476",
    "name":"Vitamin A 10,000 IU (125 caplets)",
    "description":"Vitamin A is essential for normal and night vision, and helps maintain healthy skin and mucous membranes.",
    "image_title":"vitamin-a_600px",
    "image":"https://hplussport.com/wp-content/uploads/2016/12/vitamin-A_600px.png",
    "size": "large",
    "price": "600"},
    {"id":"477",
    "name":"Vitamin C 1000 mg (100 tablets)",
    "description":"Protects against free radicals and supports the immune system.",
    "image_title":"vitamin-c_600px",
    "image":"https://hplussport.com/wp-content/uploads/2016/12/vitamin-C_600px.png",
    "size": "large",
    "price": "2000"},
    {"id":"478",
    "name":"Vitamin B-Complex (100 caplets)",
    "description":"Contains a combination of essential B vitamins that help convert food to energy.",
    "image_title":"b-complex_600px",
    "image":"https://hplussport.com/wp-content/uploads/2016/12/B-complex_600px.png",
    "size": "large",
    "price": "3000"}
 ]
}
];

export default SHOP_DATA;